#!/bin/bash

clear


echo "SCRIPT PENTRU RESTAURARE/BACKUP"
echo 
echo "BACKUP ---- 1"
echo
echo "RESTORE --- 2"
echo
echo
echo



read -p "NUMAR:" nr

if [ $nr -eq 1 ]
then
echo
echo "introdu usernameul pentru baza de date"
read -p "USR:" usrmysql
echo
echo
echo "introdu numele bazei de date "
read -p "NBAZADATE:" namesql
echo
echo
echo "alege unde vrei sa se salveze baza de date ex(/home/server1/Documents/backup/backup.sql "
read -p "pathptbazadedate:" pathsql
mysqldump --single-transaction -u $usrmysql -p $namesql > $pathsql
echo
echo 
echo "alege unde vrei sa salvezi backupul fisierelor wordpress ex(/home/server1/Documents/backup/backup.tar"
read -p "locatiebackupwp:" locwp
echo
echo 
echo "alege la ce director wp vrei sa faci backup ex(/var/www/html/wordpress ."
read -p "backuppoint:"  wpbackup
tar cvf $locwp -C $wpbackup


       fi


if [ $nr -eq 2 ]
then
echo
echo
echo "RESTAURARE BACKUP: "
echo
echo
echo
echo "introdu usernameul pentru baza de date"
read -p "USR:" usrmysql
echo
echo
echo "introdu numele bazei de date "
read -p "NBAZADATE:" namesql
echo
echo
echo "alege din ce locatie  vrei sa faci restore la  baza de date ex(/home/server1/Documents/backup/backup.sql "
read -p "pathptbazadedate:" pathsql
mysql -u $usrmysql -p $namesql < $pathsql
echo
echo
echo "alege de unde vrei sa restaurezi backupul fisierelor wordpress ex(/home/server1/Documents/backup/backup.tar"
read -p "locatiebackupwp:" locwp
echo
echo
echo "alege la ce director vrei sa rescrii din backup ex(/var/www/html/wordpress ."
read -p "backuppoint:"  wpbackup
tar xvf $locwp -C $wpbackup 

       fi


